site_name: Shawn's Opinionated Guide to Code
site_author: Shawn Witte
site_url: https://minirogue.github.io/shawns-guide-to-code
site_description: Articles detailing the coding opinions of Shawn Witte.
repo_url: https://github.com/Minirogue/shawns-guide-to-code/

plugins:
  - search
  - mermaid2
  - rss
  - tags:
      tags: false
      tags_allowed:
        - Kotlin
        - Code Style

hooks:
  - hooks/add-git-history.py
  - hooks/add-watched-files.py

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - attr_list

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  favicon: img/shawnicon.ico
  logo: img/shawnicon.ico
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to pastel
    # Custom
    - media: "(prefers-color-scheme: pastel)"
      scheme: pastel
      toggle:
        icon: material/looks
        name: Switch to system preference
extra_css:
  - css/rainbow_in_the_dark.css
